movies/urls.py
from django.urls import path

from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.ListView, name='index'),
    path('search/', views.search_movies, name='search'),
    path('create/', views.CreateView, name='create'),
    path('<int:movie_id>/', views.DetailView, name='detail'),
    path('update/<int:movie_id>/', views.UpdateView, name='update'),
    path('delete/<int:movie_id>/', views.DeleteView, name='delete'),
    path('<int:movie_id>/comment/', views.create_comment, name='comment'),
    path('lists/', views.ListListView.as_view(), name='lists'),
    path('lists/create', views.ListCreateView.as_view(), name='create-list'),
    path('lists/tecnology', views.DetailList, name='detail-list'),
]

moviesite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'),
    path('', views.index, name='index'),
]

movies/models.py
from django.db import models
from django.conf import settings


class Post(models.Model):
    name = models.CharField(max_length=255)
    release_year = models.TextField()
    poster_url = models.URLField(max_length=200, null=True)
    date_post = models.DateTimeField()

    def __str__(self):
        return f'{self.name} ({self.release_year})'


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    likes = models.DateTimeField()
    movie = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

class Category(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField()
    movies = models.ManyToManyField(Post)

    def __str__(self):
        return f'{self.name} by {self.author}'

staticpages/models.py
from django.db import models

# Create your models here.

movies/forms.py
from django.forms import ModelForm
from .models import Post, Comment, Category


class MovieForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'name',
            'release_year',
            'poster_url',
            'date_post',
        ]
        labels = {
            'name': 'Título',
            'release_year': 'Texto',
            'poster_url': 'URL do Poster',
            'date_post': 'Data de Publicação'
        }

class ReviewForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'text',
            'likes',
        ]
        labels = {
            'author': 'Usuário',
            'text': 'Comentário',
            'likes': 'Data de Publicação',
        }

class CreateList(ModelForm):
    class Meta:
        model = Category
        fields = [
            'author',
            'name',
            'description',
            'movies',
        ]
        labels = {
            'author': 'Usuário',
            'name': 'Nome da Categoria',
            'description': 'Descrição',
            'movies': 'Posts',
        }

movies/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from .temp_data import movie_data
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment, Category
from .forms import ReviewForm, CreateList
from django.views import generic

def DetailView(request, movie_id):
    movie = get_object_or_404(Post, pk=movie_id)
    context = {'movie': movie}
    return render(request, 'movies/detail.html', context)


def search_movies(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        movie_list = Post.objects.filter(name__icontains=search_term)
        context = {"movie_list": movie_list}
    return render(request, 'movies/search.html', context)


def CreateView(request):
    if request.method == 'POST':
        movie_name = request.POST['name']
        movie_release_year = request.POST['release_year']
        movie_poster_url = request.POST['poster_url']
        movie_date_post = request.POST['date_post']
        movie = Post(name=movie_name,
                      release_year=movie_release_year,
                      poster_url=movie_poster_url,
                      date_post=movie_date_post)
        movie.save()
        return HttpResponseRedirect(
            reverse('movies:detail', args=(movie.id, )))
    else:
        return render(request, 'movies/create.html', {})

def ListView(request):
    movie_list = Post.objects.all()
    context = {'movie_list': movie_list}
    return render(request, 'movies/index.html', context)

def UpdateView(request, movie_id):
    movie = get_object_or_404(Post, pk=movie_id)

    if request.method == "POST":
        movie.name = request.POST['name']
        movie.release_year = request.POST['release_year']
        movie_poster_url = request.POST['poster_url']
        movie.save()
        return HttpResponseRedirect(
            reverse('movies:detail', args=(movie.id, )))

    context = {'movie': movie}
    return render(request, 'movies/update.html', context)


def DeleteView(request, movie_id):
    movie = get_object_or_404(Post, pk=movie_id)

    if request.method == "POST":
        movie.delete()
        return HttpResponseRedirect(reverse('movies:index'))

    context = {'movie': movie}
    return render(request, 'movies/delete.html', context)

def create_comment(request, movie_id):
    movie = get_object_or_404(Post, pk=movie_id)
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            comment_author = form.cleaned_data['author']
            comment_text = form.cleaned_data['text']
            comment_likes = form.cleaned_data['likes']
            comment = Comment(author=comment_author,
                            text=comment_text,
                            likes=comment_likes,
                            movie=movie)
            comment.save()
            return HttpResponseRedirect(
                reverse('movies:detail', args=(movie_id, )))
    else:
        form = ReviewForm()
    context = {'form': form, 'movie': movie}
    return render(request, 'movies/review.html', context)

class ListListView(generic.ListView):
    model = Category
    template_name = 'movies/lists.html'

class ListCreateView(generic.CreateView):
    model = Category
    template_name = 'movies/create_list.html'
    fields = ['name', 'author', 'description', 'movies']
    success_url = reverse_lazy('movies:lists')

def DetailList(request):
    category = get_object_or_404(Category)
    context = {'category': category}
    return render(request, 'movies/detail_list.html', context)

staticpages/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

movies/templates/movies/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Novo Post</h2>
<form method="POST" action="{% url 'movies:create' %}">
    {% csrf_token %}
    <p>
        <label for="id_name">Título:</label>
        <input type="text" name="name" id="id_name" />
    </p>
    <p>
        <label for="id_release_year">Texto:</label>
        <input type="text" name="release_year" id="id_release_year" />
    </p>
    <p>
        <label for="id_poster_url">URL da Imagem:</label>
        <input type="url" name="poster_url" id="id_poster_url" />
    </p>
    <p>
        <label for="id_date_post">Data de Publicação:</label>
        <input type="datetime" name="date_post" id="id_date_post" />
    </p>
    <button type="submit">Criar</button>
</form>

{% endblock content %}

movies/templates/movies/create_list.html
{% extends 'base.html' %}

{% block title %}
Criar Post
{% endblock title %}

{% block content %}
<h2>Criar Categoria</h2>

<form action="{% url 'movies:create-list' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

movies/templates/movies/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'movies:delete' movie.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar o post? "{{ movie.name }}"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block title %}
{{ movie.name }} ({{ movie.release_year }}
{% endblock title %}

{% block content %}
<h2>{{ movie.name }}</h2>

<section class="dados-de-filme">
    <img src="{{ movie.poster_url }}" alt="Poster do filme {{ movie.name}}">
    <ul>
        <li>Título: {{ movie.name }}</li>
        <li>Texto: {{ movie.release_year }} </li>
        <li>Data de Publicação: {{ movie.date_post }}</li>
        {% if movie.category_set.all %}
            <li>Incluso nas categorias: {{ movie.category_set.all|join:", " }} </li>
        {% endif %}
        <li><a href="{% url 'movies:update' movie.id %}">Editar</a></li>
        <li><a href="{% url 'movies:delete' movie.id %}">Apagar</a></li>
    </ul>
</section>

<hr>

<section>
    <header>
        <h3>Comentários</h3>
    </header>
    <ul>
        {% if movie.comment_set.all %}
        {% for comment in movie.comment_set.all %}
            <figure>
                <blockquote>
                    "{{ comment.text }}"
                </blockquote>
                <figcaption>—{{ comment.author }}
                <figcaption>{{ comment.likes }}
            </figure>
        {% endfor %}
        {% else %}
        <p>Ainda não existe nenhum comentário para este filme.</p>
        {% endif %}
    </ul>
    <hr>
    <a href="{% url 'movies:comment' movie.pk %}"><button>Comente!</button></a>
</section>

{% endblock content %}

movies/templates/movies/detail_list.html
{% extends 'base.html' %}

{% block title %}
{{ movie.name }} ({{ movie.release_year }}
{% endblock title %}

{% block content %}
<h2>{{ movie.name }}</h2>

<section class="dados-de-categoria">
    <ul>
        <li>Categoria: {{ category.name }}</li>
        <li>Texto: {{ category.description }} </li>
        <li>Autor: {{ category.author }}</li>
    </ul>
    <div class="lista-de-cards">
        {% for movie in category.movies.all %}
        <div class="card">
            <a href="{% url 'movies:detail' movie.id %}"><img src="{{ movie.poster_url }}"
                    alt="Poster do filme {{ movie.name}}"></a>
            <p>{{ movie.name }} ({{ movie.release_year }})</p>
        </div>
        {% endfor %}
    </div>
</section>

{% endblock content %}

movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Todos os Posts</h2>
<section>
    <p>Muitos resultados? <a href="{% url 'movies:search' %}">Buscar Posts</a></p>
    <p>Não encontrou o post? <a href="{% url 'movies:create' %}">Adicionar Novo Post</a></p>
</section>
{% if movie_list %}
<section class="lista-de-cards">
    {% for movie in movie_list %}
    <article class="card">
        <a href="{% url 'movies:detail' movie.id %}"><img src="{{ movie.poster_url }}"
                alt="Poster do filme {{ movie.name}}"></a> <!-- modifique esta linha -->
        <p>{{ movie.name }}</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum filme.</p>
{% endif %}

{% endblock content %}

movies/templates/movies/lists.html
{% extends 'base.html' %}

{% block title %}
Listas
{% endblock title %}

{% block content %}
<h2>Categorias de Posts</h2>

<section>
    {% for category in category_list %}
    <hr>
    <article>
        <header>
            <h3>{{category.name}} (de {{ category.author }}) </h3>
            <h>{{category.description}}</h>
            <a href="{% url 'movies:detail-list' %}"><button>Acesse a categoria</button></a>
        </header>
        <div class="lista-de-cards">
            {% for movie in category.movies.all %}
            <div class="card">
                <a href="{% url 'movies:detail' movie.id %}"><img src="{{ movie.poster_url }}"
                        alt="Poster do filme {{ movie.name}}"></a>
                <p>{{ movie.name }} ({{ movie.release_year }})</p>
            </div>
            {% endfor %}
        </div>
    </article>
    {% endfor %}

    <a href="{% url 'movies:create-list' %}"><button>Crie sua Categoria</button></a>
</section>

{% endblock content %}

movies/templates/movies/review.html
{% extends 'base.html' %}

{% block content %}
<h2>Comentar Post {{ movie.name }} </h2>

<form action="{% url 'movies:comment' movie.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar Comentário</button>
</form>

<p><a href="{% url 'movies:detail' movie.id %}">Voltar para a página do post</a></p>
{% endblock content %}

movies/templates/movies/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de Posts por Nome</h2>
<form action="{% url 'movies:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if movie_list %}
<section class="lista-de-cards">
    {% for movie in movie_list %}
    <article class="card">
        <img src="{{ movie.poster_url }}" alt="Poster do filme {{ movie.name}}">
        <p>{{ movie.name }} ({{ movie.release_year }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum post para a busca.</p>
{% endif %}

{% endblock content %}

movies/templates/movies/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar Dados do Post: {{ movie.name }}</h2>
<form method="POST" action="{% url 'movies:update' movie.id%}">
    {% csrf_token %}
    <p>
        <label for="id_name">Título:</label>
        <input type="text" name="name" id="id_name" value="{{ movie.name }}" />
    </p>
    <p>
        <label for=" id_release_year">Ano de Lançamento:</label>
        <input type="text" name="release_year" id="id_release_year" value="{{ movie.release_year }}" />
    </p>
    <p>
        <label for=" id_poster_url">URL da Imagem:</label>
        <input type="url" name="poster_url" id="id_poster_url" value="{{movie.poster_url}}" />
    </p>
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre este site</h2>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1><i>Express Yourself!</i></h1>
<p>O Blog que trata de todo assunto do cotidiano</p>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Express Yourself!
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'logo2.svg' %}" width="200" height="100"> </a>
        <nav id="navegacao-principal">
            <ul>
                <li><a href="{% url 'movies:index' %}">Posts</a></li>
                <li><a href="{% url 'movies:lists' %}">Categorias</a></li> <!-- adicionar esta linha -->
                <li><a href="{% url 'about' %}">Sobre</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2022</small>
        </p>
    </footer>
</body>

</html>